### PR TITLE
assignment complete - remove console log

### PR DESCRIPTION
**Pull request by lsimmons1832**

### CODE REVIEW

**Comment by morecallan** [comment]
@lsimmons1832 - Great work on this! Your base requirements are done and it just needs a few tweaks.
- There is one bug that if I hit the "Enter" key while in the input field, the whole page reloads.
- Your counter is pretty cool, but what happens if I wanted to add 10 more cars to my lot? Could you think about a flexible solution for that?

**Comment by lsimmons1832** [comment]
I fixed the bug.  I should have used modulo instead of hard coding the value for my counter.

**Comment by zoeames** [comment]
@lsimmons1832 very very very close.  Only issue I see is when i click on a card and start typing in the input and then click on another card the text i typed for the first card still shows up.  Either: 1.  clear out your input each time you focus or 2.  put the text that appears on the card in the input

**Comment by zoeames** [comment]
looks good 👍

**Pull request merged**
